### ISSUE TITLE
Cross checking issue # 79 failed

### ISSUE THREAD

**Issue by Romasa** [aukgit/WeReviewProject#90] opened 2016-04-30 03:28 UTC
Checking issue# [79](https://github.com/aukgit/WeReviewProject/issues/79) ended up in broken code
![image](https://cloud.githubusercontent.com/assets/3047801/14933603/a7f11532-0eb5-11e6-99cc-1b80558c6088.png)

**Comment by aukgit** [comment] 2016-04-30 07:36
This is not an issue:
http://stackoverflow.com/questions/5767768/troubleshooting-anti-forgery-token-problems
This is because you may have double clicked on the button.. for production there will be nice error message saying there is something went wrong or you have double clicked on the button . Please remove the cache and try again.

**Comment by aukgit** [comment] 2016-04-30 07:38
http://forums.asp.net/t/1560362.aspx?A+required+anti+forgery+token+was+not+supplied+or+was+invalid

Or may be: 
This behavior is correct.  The anti-forgery tokens are tied to specific users (or the 'guest' user if the current user is not logged in).  The first time the form is generated, the user is not logged in, so a token is generated for the user GUEST.  The user hits the login button, the token validates correctly (since the user has not yet been logged in), your controller logs the user in, and life is good.  Let's assume he logged in as JOE.

Now, if the user hits the back button, he'll be taken back to the original form.  (More specifically, he'll see the cached version of the original form, complete with GUEST token.)  When he tries to submit the login again, the GUEST token cannot be used for a request coming from JOE, so the system rejects the token.

This is pretty much the same behavior you'll see at some banking and other web sites, many of which don't allow you to use the back button once you've logged in.  Their tokens follow a similar pattern of being tied to a specific user, and if an old token is used with a logged-in user they will fail.

Presumably this shouldn't be problematic, as the particular scenario under consideration (submitting the exact same form under two different identities) isn't something most users do and isn't something that's always expected to work properly.  If this is however a problem for you, you could remove [ValidateAntiForgeryToken] from the Login() action.

**Comment by Romasa** [comment] 2016-04-30 09:12
i have removed the cache. Even checked by opening a new browser, I am
receiving the same behaviour. Not for this particular test case, I tried to
change the admin email and I am receiving the same problem. Please check it.

On Sat, Apr 30, 2016 at 1:38 PM, Alim Ul Karim notifications@github.com
wrote:

> http://forums.asp.net/t/1560362.aspx?A+required+anti+forgery+token+was+not+supplied+or+was+invalid
> 
> Or may be:
> This behavior is correct. The anti-forgery tokens are tied to specific
> users (or the 'guest' user if the current user is not logged in). The first
> time the form is generated, the user is not logged in, so a token is
> generated for the user GUEST. The user hits the login button, the token
> validates correctly (since the user has not yet been logged in), your
> controller logs the user in, and life is good. Let's assume he logged in as
> JOE.
> 
> Now, if the user hits the back button, he'll be taken back to the original
> form. (More specifically, he'll see the cached version of the original
> form, complete with GUEST token.) When he tries to submit the login again,
> the GUEST token cannot be used for a request coming from JOE, so the system
> rejects the token.
> 
> This is pretty much the same behavior you'll see at some banking and other
> web sites, many of which don't allow you to use the back button once you've
> logged in. Their tokens follow a similar pattern of being tied to a
> specific user, and if an old token is used with a logged-in user they will
> fail.
> 
> Presumably this shouldn't be problematic, as the particular scenario under
> consideration (submitting the exact same form under two different
> identities) isn't something most users do and isn't something that's always
> expected to work properly. If this is however a problem for you, you could
> remove [ValidateAntiForgeryToken] from the Login() action.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/aukgit/WeReviewProject/issues/90#issuecomment-215944570

## 

Holy is my Lord, the Magnificent.

Allah listens to him who praises Him. Our Lord, to You is due all praise.

**Comment by aukgit** [comment] 2016-05-02 06:47
Then will you please write the reproduce steps.

**Comment by aukgit** [comment] 2016-05-07 20:09
Reproduce steps are not shown.. Thus closing this issue.

**Closed as completed by aukgit** 2016-05-07 20:09 UTC
Labels: question

**Comment by Romasa** [comment] 2016-05-12 10:21
Thanks for 500 error page but this problem persists. I need to change password for an account and it is showing this 500 internal server error. You can follow the steps below:
1. click on the Login button
2. click on the Forget Password button
3. enter the email address for which you want to change your password

After Step # 3 I am getting this 500 error.

Note: I have installed firefox afresh.
